#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v2
# autospec commit: e661f3a
#
Name     : liblangtag
Version  : 0.6.6
Release  : 6
URL      : https://bitbucket.org/tagoh/liblangtag/downloads/liblangtag-0.6.6.tar.bz2
Source0  : https://bitbucket.org/tagoh/liblangtag/downloads/liblangtag-0.6.6.tar.bz2
Summary  : Interface to access tags for identifying languages
Group    : Development/Tools
License  : LGPL-3.0
Requires: liblangtag-data = %{version}-%{release}
Requires: liblangtag-lib = %{version}-%{release}
Requires: liblangtag-license = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : gobject-introspection-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libxslt-bin
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(check)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(libxml-2.0)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
liblangtag
=============
An interface library to access tags for identifying languages

%package data
Summary: data components for the liblangtag package.
Group: Data

%description data
data components for the liblangtag package.


%package dev
Summary: dev components for the liblangtag package.
Group: Development
Requires: liblangtag-lib = %{version}-%{release}
Requires: liblangtag-data = %{version}-%{release}
Provides: liblangtag-devel = %{version}-%{release}
Requires: liblangtag = %{version}-%{release}

%description dev
dev components for the liblangtag package.


%package doc
Summary: doc components for the liblangtag package.
Group: Documentation

%description doc
doc components for the liblangtag package.


%package lib
Summary: lib components for the liblangtag package.
Group: Libraries
Requires: liblangtag-data = %{version}-%{release}
Requires: liblangtag-license = %{version}-%{release}

%description lib
lib components for the liblangtag package.


%package license
Summary: license components for the liblangtag package.
Group: Default

%description license
license components for the liblangtag package.


%prep
%setup -q -n liblangtag-0.6.6
cd %{_builddir}/liblangtag-0.6.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1701093410
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1701093410
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/liblangtag
cp %{_builddir}/liblangtag-%{version}/COPYING %{buildroot}/usr/share/package-licenses/liblangtag/f45ee1c765646813b442ca58de72e20a64a7ddba || :
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/LangTag-0.6.typelib
/usr/share/gir-1.0/*.gir
/usr/share/liblangtag/common/bcp47/calendar.xml
/usr/share/liblangtag/common/bcp47/collation.xml
/usr/share/liblangtag/common/bcp47/currency.xml
/usr/share/liblangtag/common/bcp47/number.xml
/usr/share/liblangtag/common/bcp47/timezone.xml
/usr/share/liblangtag/common/bcp47/transform.xml
/usr/share/liblangtag/common/bcp47/transform_ime.xml
/usr/share/liblangtag/common/bcp47/transform_keyboard.xml
/usr/share/liblangtag/common/bcp47/transform_mt.xml
/usr/share/liblangtag/common/bcp47/transform_private_use.xml
/usr/share/liblangtag/common/bcp47/variant.xml
/usr/share/liblangtag/common/supplemental/likelySubtags.xml
/usr/share/liblangtag/common/supplemental/supplementalData.xml
/usr/share/liblangtag/common/supplemental/supplementalMetadata.xml
/usr/share/liblangtag/language-subtag-registry.xml

%files dev
%defattr(-,root,root,-)
/usr/include/liblangtag/langtag.h
/usr/include/liblangtag/lt-config.h
/usr/include/liblangtag/lt-database.h
/usr/include/liblangtag/lt-error.h
/usr/include/liblangtag/lt-ext-module-data.h
/usr/include/liblangtag/lt-ext-module.h
/usr/include/liblangtag/lt-extension.h
/usr/include/liblangtag/lt-extlang-db.h
/usr/include/liblangtag/lt-extlang.h
/usr/include/liblangtag/lt-gobject.h
/usr/include/liblangtag/lt-grandfathered-db.h
/usr/include/liblangtag/lt-grandfathered.h
/usr/include/liblangtag/lt-iter.h
/usr/include/liblangtag/lt-lang-db.h
/usr/include/liblangtag/lt-lang.h
/usr/include/liblangtag/lt-list.h
/usr/include/liblangtag/lt-macros.h
/usr/include/liblangtag/lt-messages.h
/usr/include/liblangtag/lt-redundant-db.h
/usr/include/liblangtag/lt-redundant.h
/usr/include/liblangtag/lt-region-db.h
/usr/include/liblangtag/lt-region.h
/usr/include/liblangtag/lt-relation-db.h
/usr/include/liblangtag/lt-script-db.h
/usr/include/liblangtag/lt-script.h
/usr/include/liblangtag/lt-string.h
/usr/include/liblangtag/lt-tag.h
/usr/include/liblangtag/lt-utils.h
/usr/include/liblangtag/lt-variant-db.h
/usr/include/liblangtag/lt-variant.h
/usr/include/liblangtag/lt-xml.h
/usr/lib64/liblangtag-gobject.so
/usr/lib64/liblangtag.so
/usr/lib64/pkgconfig/liblangtag-gobject.pc
/usr/lib64/pkgconfig/liblangtag.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/gtk-doc/html/liblangtag/Container.html
/usr/share/gtk-doc/html/liblangtag/Module.html
/usr/share/gtk-doc/html/liblangtag/Utilities.html
/usr/share/gtk-doc/html/liblangtag/annotation-glossary.html
/usr/share/gtk-doc/html/liblangtag/api-index-full.html
/usr/share/gtk-doc/html/liblangtag/ch01.html
/usr/share/gtk-doc/html/liblangtag/home.png
/usr/share/gtk-doc/html/liblangtag/index.html
/usr/share/gtk-doc/html/liblangtag/left-insensitive.png
/usr/share/gtk-doc/html/liblangtag/left.png
/usr/share/gtk-doc/html/liblangtag/liblangtag-Container---Extension.html
/usr/share/gtk-doc/html/liblangtag/liblangtag-Container---Extlang.html
/usr/share/gtk-doc/html/liblangtag/liblangtag-Container---Grandfathered.html
/usr/share/gtk-doc/html/liblangtag/liblangtag-Container---Language.html
/usr/share/gtk-doc/html/liblangtag/liblangtag-Container---Redundant.html
/usr/share/gtk-doc/html/liblangtag/liblangtag-Container---Region.html
/usr/share/gtk-doc/html/liblangtag/liblangtag-Container---Script.html
/usr/share/gtk-doc/html/liblangtag/liblangtag-Container---Tag.html
/usr/share/gtk-doc/html/liblangtag/liblangtag-Container---Variant.html
/usr/share/gtk-doc/html/liblangtag/liblangtag-Database---Extlang.html
/usr/share/gtk-doc/html/liblangtag/liblangtag-Database---Grandfathered.html
/usr/share/gtk-doc/html/liblangtag/liblangtag-Database---Language.html
/usr/share/gtk-doc/html/liblangtag/liblangtag-Database---Redundant.html
/usr/share/gtk-doc/html/liblangtag/liblangtag-Database---Region.html
/usr/share/gtk-doc/html/liblangtag/liblangtag-Database---Relation.html
/usr/share/gtk-doc/html/liblangtag/liblangtag-Database---Script.html
/usr/share/gtk-doc/html/liblangtag/liblangtag-Database---Variant.html
/usr/share/gtk-doc/html/liblangtag/liblangtag-Database.html
/usr/share/gtk-doc/html/liblangtag/liblangtag-Doubly-Linked-Lists.html
/usr/share/gtk-doc/html/liblangtag/liblangtag-Error.html
/usr/share/gtk-doc/html/liblangtag/liblangtag-Iterator.html
/usr/share/gtk-doc/html/liblangtag/liblangtag-Miscellaneous-Macros.html
/usr/share/gtk-doc/html/liblangtag/liblangtag-Module---Accessor.html
/usr/share/gtk-doc/html/liblangtag/liblangtag-Module---Data.html
/usr/share/gtk-doc/html/liblangtag/liblangtag-Strings.html
/usr/share/gtk-doc/html/liblangtag/liblangtag.devhelp2
/usr/share/gtk-doc/html/liblangtag/right-insensitive.png
/usr/share/gtk-doc/html/liblangtag/right.png
/usr/share/gtk-doc/html/liblangtag/style.css
/usr/share/gtk-doc/html/liblangtag/up-insensitive.png
/usr/share/gtk-doc/html/liblangtag/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/liblangtag-gobject.so.0
/usr/lib64/liblangtag-gobject.so.0.3.0
/usr/lib64/liblangtag.so.1
/usr/lib64/liblangtag.so.1.4.1
/usr/lib64/liblangtag/liblangtag-ext-ldml-t.so
/usr/lib64/liblangtag/liblangtag-ext-ldml-u.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/liblangtag/f45ee1c765646813b442ca58de72e20a64a7ddba
